### ISSUE TITLE
Incorrect weather icons

### ISSUE THREAD

**Issue by martinsefcik** [samvdb/loxone-weather-proxy#1]
It looks like after moving to tomorrow API some icons are not correctly showing. Outside is 20-25C and icon is light snow showers or heavy snow or some icons are completly missing.

**Comment by samvdb** [comment]
Hi,

I noticed the same, i did a very quick matching of the icons without testing.
I don't have much time for the moment, any help is much appreciated.

https://github.com/samvdb/loxone-weather-proxy/blob/master/tomorrow_icons.go

I'm guessing the loxone codes are wrong for cases 1000-2000, which is showing snow instead of sun / clouds.

**Comment by samvdb** [comment]
Fixed by #3
